Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: app.lambda_handler
      CodeUri: /Users/kylereaves/src/nlp-app/nlp_app
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          DOCKER_HOST: unix:///var/run/docker.sock