version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "nlp-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-rr249c6daol6"
s3_prefix = "nlp-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
