AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  nlp-app

  Sample SAM Template for nlp-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Tracing: Active
    Environment:
      Variables:
        NLTK_DATA: /tmp/nltk_data


Resources:
  NLPFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: nlp_app/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
#      Events:
#        NLP:
#          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
#          Properties:
#            Path: /hello
#            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
#  NLPApi:
#    Description: "API Gateway endpoint URL for Prod stage for nlp-app function"
#    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  NLPFunction:
    Description: "nlp-app Lambda Function ARN"
    Value: !GetAtt NLPFunction.Arn
#  NLPFunctionIamRole:
#    Description: "Implicit IAM Role created for nlp-app function"
#    Value: !GetAtt NLPFunctionRole.Arn
