AWSTemplateFormatVersion: '2010-09-09'
Description: AWS SAM CLI Nested Stack for Auto Dependency Layer Creation
Metadata:
  SamCliInfo: 1.66.0
  key: AWS SAM CLI sync command
Outputs:
  NLPFunction2ef82f99DepLayer:
    Value:
      Ref: NLPFunction2ef82f99DepLayer
Resources:
  NLPFunction2ef82f99DepLayer:
    Metadata:
      CreatedBy: AWS SAM CLI sync command
    Properties:
      CompatibleRuntimes:
      - python3.9
      ContentUri: /Users/kylereaves/src/nlp-app/.aws-sam/auto-dependency-layer/NLPFunction2ef82f99DepLayer
      Description: Auto created layer for dependencies of function NLPFunction
      LayerName: nlp-app834d5234-NLPFunction2ef82f99-DepLayer
      RetentionPolicy: Delete
    Type: AWS::Serverless::LayerVersion
Transform: AWS::Serverless-2016-10-31
